language: minimal

sudo: required

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - make build
        - make test
    - stage: tag
      if: branch = master AND tag IS blank
      script: make tag
    - stage: release
      if: tag IS present
      script: make release
