version: "3.4"

services:
  app:
    image: "climbcomp/climbcomp-ruby:${DOCKER_TAG:-latest}"
    environment:
      - GEM_HOST_API_KEY
      - GH_TOKEN
      - TRAVIS_BRANCH
      - TRAVIS_PULL_REQUEST
      - TRAVIS_REPO_SLUG
      - VERSION_SRC_PATH=./lib/climbcomp/version.rb
    build:
      context: "."
    volumes:
      - ".:/usr/src/app"
