# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: climbcomp/account/v1/user.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "climbcomp.account.v1.User" do
    optional :id, :string, 1
    optional :created_time, :message, 2, "google.protobuf.Timestamp"
    optional :updated_time, :message, 3, "google.protobuf.Timestamp"
    optional :username, :string, 4
    optional :email, :string, 5
  end
end

module Climbcomp
  module Account
    module V1
      User = Google::Protobuf::DescriptorPool.generated_pool.lookup("climbcomp.account.v1.User").msgclass
    end
  end
end
