# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: climbcomp/meta/v1/meta_api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "climbcomp.meta.v1.GetVersionRequest" do
  end
  add_message "climbcomp.meta.v1.GetVersionResponse" do
    optional :version, :string, 1
  end
end

module Climbcomp
  module Meta
    module V1
      GetVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("climbcomp.meta.v1.GetVersionRequest").msgclass
      GetVersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("climbcomp.meta.v1.GetVersionResponse").msgclass
    end
  end
end
